ToDo Application
Sinawo/TaskPlanning-App pull request #1
Opened 2024-11-11 02:31 UTC by Sinawo

This is  a todo-list management application to allow users to collaborate and track tasks

2024-11-11 09:43 UTC, TshepoMagagula requested changes
![Screenshot_11-11-2024_111831_127 0 0 1](https://github.com/user-attachments/assets/150e12f4-9b65-4a33-8969-f1b3e44bc03b)

@Sinawo This is how the project appears when I try to run it on my live server. Give a detailed guide on you README file to the user on how to successfully run your project on their local machine.

2024-11-11 11:47 UTC, TshepoMagagula requested changes
![Screenshot_11-11-2024_134150_localhost](https://github.com/user-attachments/assets/2a738097-6a75-4f20-9cee-fe98418ba650)

@Sinawo make the web application responsive, as you can see the header elements are squashed together on a smaller display

2024-11-12 07:23 UTC, Sinawo commented
> ![Screenshot_11-11-2024_111831_127 0 0 1](https://private-user-images.githubusercontent.com/127089823/384866849-150e12f4-9b65-4a33-8969-f1b3e44bc03b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTU2MzcsIm5iZiI6MTczMTM5NTMzNywicGF0aCI6Ii8xMjcwODk4MjMvMzg0ODY2ODQ5LTE1MGUxMmY0LTliNjUtNGEzMy04OTY5LWYxYjNlNDRiYzAzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMDcwODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRjN2NiODMxMmU1ZWI5ZWExYWJlYzQzNmQ2M2U0YTlkNjcxNGQwN2RkMmFjZmUxMjQxZDEwZDhkMzlmNWY2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bsGZojLp1toNHfkvKIk-ml71mr127ezLjBoW-h6KVPs)
> 
> @Sinawo This is how the project appears when I try to run it on my live server. Give a detailed guide on you README file to the user on how to successfully run your project on their local machine.



> ![Screenshot_11-11-2024_111831_127 0 0 1](https://private-user-images.githubusercontent.com/127089823/384866849-150e12f4-9b65-4a33-8969-f1b3e44bc03b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTU2NjcsIm5iZiI6MTczMTM5NTM2NywicGF0aCI6Ii8xMjcwODk4MjMvMzg0ODY2ODQ5LTE1MGUxMmY0LTliNjUtNGEzMy04OTY5LWYxYjNlNDRiYzAzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMDcwOTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk0ZDQyMDhiMjg1NzU1NjY1MDBiNGJjZDBhMWYwNzMzY2NjNjYyM2U3MDBmYzQyM2Y2N2JmM2MzMzlmNjk0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cqixPzQL4t5vZis4i2mSVMoKijKtnEG7Tkg4vNP7okg)
> 
> @Sinawo This is how the project appears when I try to run it on my live server. Give a detailed guide on you README file to the user on how to successfully run your project on their local machine.

@TshepoMagagula Hey Tshepo, I see you've already figured it out. To run the project after you have installed the dependencies use npm start

2024-11-12 07:56 UTC, BAHLEMAJOLA commented on create-pdf.py
> +    pdf.set_font("Arial", "", 11)
Consistent Font Sizes To improve readability, consider using a larger font size for the body text (11 might be too small, especially in printed form). A size of 12 or 13 could improve readability.

2024-11-12 10:34 UTC, NuffSaid-Bore requested changes
@Sinawo Consider making your readme file more comprehensive by providing clear instructions to follow. Proving more information on your project such as Tech Stack and tools used.

2024-11-13 12:54 UTC, TshepoMagagula approved these changes

2024-11-14 12:32 UTC, NuffSaid-Bore requested changes
@Sinawo Good work mate. Try to add alerts to notify the user. e.g alerts for errors and success messages for when a task has been added/deleted/updated.

2024-11-15 06:19 UTC, zolwethu requested changes
@Sinawo  please do more controlled error handling practices,  maybe do try-catch blocks ... unless you're going for performance-critical scenarios, then it is crucial to minimize unnecessary try-catch constructs to maintain optimal execution speed.

2024-11-15 06:19 UTC, zolwethu commented on index.js
> +const express = require('express');
You should convert to ES Modules as per instruction, change all your "required" to "import".
There's really no need for export in this case, since you're just setting up a server, but it was in the instructions

2024-11-15 12:51 UTC, zolwethu approved these changes
I see the imports, way cleaner and convenient

2024-11-15 13:38 UTC, Sinawo commented
> @Sinawo Consider making your readme file more comprehensive by providing clear instructions to follow. Proving more information on your project such as Tech Stack and tools used.

@TshepoMagagula  It should be fine now

2024-11-15 13:39 UTC, Sinawo commented
> > @Sinawo Consider making your readme file more comprehensive by providing clear instructions to follow. Proving more information on your project such as Tech Stack and tools used.
> 
> @TshepoMagagula It should be fine now

2024-11-15 13:39 UTC, closed without merging